### PR TITLE
Adding new e2e tests

### PR DESCRIPTION
**Pull request by ashahba**
This PR just adds some more test cases for `timeoutForDataDownload` and `Replicas` options.
- Added tests for more replicas than the number of nodes
- Added tests to handle improperly formatted (either negative value, or value with no time unit) for timeoutForDataDownload

### CODE REVIEW

**Comment by balajismaniam** [comment]
@ashahba If you are trying add two more test cases, please add them as separate test cases without changing the already existing test cases. FWIW: `timeoutfordatadownload` is already e2e tested: https://github.com/kubeflow/experimental-kvc/blob/master/test/e2e/kvc_test.go#L369. 

Can you also explain the rest of changes you have made in this PR.

**Comment by ashahba** [comment]
@balajismaniam The changing in other test case is actually what `GitHub` things because I moved them around 🙂 since I figured having all `S3` tests next to each other makes more sense.
The new tests bring coverage for `negative` scenarios for example which was missing so I don't think those cases where tested properly.

**Comment by balajismaniam** [comment]
@ashahba Please comment on the test cases you added and I will review them. Have you tested this manually before submitting this PR?

**Comment by balajismaniam** [comment]
I would also suggest that you make minimal changes in this PR. Moving around test is not necessary IMHO.

**Comment by ashahba** [comment]
@balajismaniam I updated PR description.
If you still don't see this as a priority, you can always reject it or even close the PR.

Thanks.

**Comment by balajismaniam** [comment]
Closing due to inactivity. Please reopen if required.

**Pull request closed without merging**
